In [ ]:
pip install hmmlearn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.4/160.4 kB 2.7 MB/s eta 0:00:00


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from hmmlearn import hmm

In [ ]:
states=["Rainy","Cloudy","Sunny"]
n_states=len(states)
print('Number of hidden states :',n_states)
observation =["Sad ","Happy"]
n_observations = len(observation)
print('Number of observation:',n_observations)

Number of hidden states : 3
Number of observation: 2


In [ ]:
state_probability = np.array([0.5,0.3,0.2])
print("\nstate probability:\n",state_probability)

transition_probability = np.array([[0.5,0.3,0.2],[0.4,0.2,0.4],[0.0,0.3,0.7]])
print("\n Transition probability:\n",transition_probability)

emission_probability = np.array([[0.9,0.1],[0.6,0.4],[0.2,0.8]])
print("\n Emission probability:\n",emission_probability)


state probability:
 [0.5 0.3 0.2]

 Transition probability:
 [[0.5 0.3 0.2]
 [0.4 0.2 0.4]
 [0.  0.3 0.7]]

 Emission probability:
 [[0.9 0.1]
 [0.6 0.4]
 [0.2 0.8]]


In [ ]:
model = hmm.CategoricalHMM(n_components=n_states)
model.startprob_ = state_probability
model.transmat_ =transition_probability
model.emissionprob_ = emission_probability

In [ ]:
observations_sequence = np.array([0,1,0,1,0,0]).reshape(-1,1)
observations_sequence
for i in observations_sequence:
  if observations_sequence[i]==0:
    print(observation[0])
  else:
     print(observation[1])

Sad 
Happy
Sad 
Happy
Sad 
Sad 


In [ ]:
#predict the most likely sequence of hidden states
hidden_states = model.predict(observations_sequence)
print("Most likely hidden states:", hidden_states)
for i in hidden_states:
  if hidden_states[i]==0:
   print(states[0])
  else:
   print(states[1])

Most likely hidden states: [0 1 0 1 0 0]
Rainy
Cloudy
Rainy
Cloudy
Rainy
Rainy
